# Generated by Django 5.1.7 on 2025-03-12 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id_funcionario', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_funcionarios/')),
                ('nome_completo', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('rg', models.CharField(blank=True, max_length=20, null=True)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], default='M', max_length=1)),
                ('data_nascimento', models.DateField()),
                ('cnh', models.CharField(blank=True, max_length=20, null=True)),
                ('validade_cnh', models.DateField(blank=True, null=True)),
                ('contato_pessoal', models.CharField(max_length=20)),
                ('contato_emergencia', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('funcao', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Contratado', 'Contratado'), ('Desligado', 'Desligado')], default='Contratado', max_length=10)),
                ('data_admissao', models.DateField()),
                ('data_mobilizacao', models.DateField(blank=True, null=True)),
                ('data_desligamento', models.DateField(blank=True, null=True)),
                ('data_desmobilizacao', models.DateField(blank=True, null=True)),
                ('cracha_vale', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
