# Generated by Django 5.1.7 on 2025-03-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], default='M', max_length=20),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='status',
            field=models.CharField(choices=[('Contratado', 'Contratado'), ('Desligado', 'Desligado')], default='Contratado', max_length=20),
        ),
    ]
