# Generated by Django 5.1.7 on 2025-03-12 18:52

import django.utils.timezone
import funcionarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_alter_funcionario_cpf_alter_funcionario_sexo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(db_index=True, max_length=14, unique=True, validators=[funcionarios.models.validar_cpf]),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=funcionarios.models.upload_funcionario),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='funcao',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='id_funcionario',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterModelTable(
            name='funcionario',
            table='funcionarios',
        ),
    ]
