# Generated by Django 5.1.7 on 2025-03-17 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionarios', '0003_funcionario_data_atualizacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treinamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_treinamento', models.CharField(choices=[('Disposições Gerais - PGR', 'Disposições Gerais - PGR'), ('Equipamentos de Proteção Individual - EPI', 'Equipamentos de Proteção Individual - EPI'), ('Segurança em Instalações e Serviços em Eletricidade', 'Segurança em Instalações e Serviços em Eletricidade'), ('Transporte, Movimentação, Armazenagem e Manuseio', 'Transporte, Movimentação, Armazenagem e Manuseio'), ('Segurança no Trabalho em Máquinas e Equipamentos', 'Segurança no Trabalho em Máquinas e Equipamentos'), ('Ergonomia', 'Ergonomia'), ('Segurança e Saúde no Trabalho na Indústria', 'Segurança e Saúde no Trabalho na Indústria'), ('Trabalho em Altura', 'Trabalho em Altura'), ('RAC - Trabalho em Altura', 'RAC - Trabalho em Altura'), ('RAC - Veículos Automotores Leves', 'RAC - Veículos Automotores Leves'), ('RAC - Operação de Equipamentos Móveis', 'RAC - Operação de Equipamentos Móveis'), ('RAC - Bloqueio, Identificação e Zero Energia', 'RAC - Bloqueio, Identificação e Zero Energia'), ('RAC - Içamento de Cargas', 'RAC - Içamento de Cargas'), ('RAC - Proteção de Máquinas', 'RAC - Proteção de Máquinas'), ('RAC - Trabalhos em Eletricidade', 'RAC - Trabalhos em Eletricidade'), ('RAC - Trabalhos a Quente', 'RAC - Trabalhos a Quente'), ('PRO - Trabalho em Altura', 'PRO - Trabalho em Altura'), ('PRO - Operação de Veículos Leves', 'PRO - Operação de Veículos Leves'), ('PRO - Operação com Equipamentos Móveis', 'PRO - Operação com Equipamentos Móveis'), ('PRO - Bloqueio e Identificação', 'PRO - Bloqueio e Identificação'), ('PRO - Içamento de Cargas', 'PRO - Içamento de Cargas'), ('PRO - Proteção de Máquinas', 'PRO - Proteção de Máquinas'), ('PRO - Trabalhos em Eletricidade', 'PRO - Trabalhos em Eletricidade'), ('PRO - Isolamento de Área', 'PRO - Isolamento de Área'), ('PRO - Ferramentas Manuais Rotativas', 'PRO - Ferramentas Manuais Rotativas'), ('PRO - Trabalhos a Quente', 'PRO - Trabalhos a Quente'), ('PGS - Regras de Ouro', 'PGS - Regras de Ouro'), ('PGS - Prevenção de Fadiga', 'PGS - Prevenção de Fadiga'), ('PGS - Grades de Piso', 'PGS - Grades de Piso'), ('Treinamento Básico de SSMA', 'Treinamento Básico de SSMA'), ('Ponte Rolante, Pórtico e Talha Elétrica', 'Ponte Rolante, Pórtico e Talha Elétrica'), ('Sinaleiro/Amarrador de Cargas', 'Sinaleiro/Amarrador de Cargas'), ('Brigadeiro Auxiliar de Emergência', 'Brigadeiro Auxiliar de Emergência'), ('Ferramentas Abrasivas', 'Ferramentas Abrasivas'), ('Treinamento Montagem/Desmontagem Andaime', 'Treinamento Montagem/Desmontagem Andaime'), ('Operação Plataforma Trabalho Aéreo', 'Operação Plataforma Trabalho Aéreo'), ('Operações de Soldagem e Corte a Quente', 'Operações de Soldagem e Corte a Quente'), ('Uso de Máquina de Solda', 'Uso de Máquina de Solda'), ('Inspeção de Acessórios de Içamento de Cargas', 'Inspeção de Acessórios de Içamento de Cargas'), ('Operador de Guindaste Veicular (Caminhão Munck)', 'Operador de Guindaste Veicular (Caminhão Munck)'), ('PTS - Executante Credenciado', 'PTS - Executante Credenciado'), ('PTS - Emitente', 'PTS - Emitente'), ('ART - Análise de Risco da Tarefa', 'ART - Análise de Risco da Tarefa'), ('Noções de Primeiros Socorros', 'Noções de Primeiros Socorros'), ('Operador de Plataformas Elevatórias', 'Operador de Plataformas Elevatórias')], max_length=255)),
                ('norma', models.CharField(max_length=50)),
                ('carga_horaria', models.TimeField(blank=True, null=True)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('validade_certificado', models.DateField(blank=True, null=True)),
                ('validade_passaporte', models.DateField(blank=True, null=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.funcionario')),
            ],
        ),
    ]
